### ISSUE TITLE
BUG: Description/Data Inconsistent

### ISSUE THREAD

**Issue by lumbar527** [OcelotWalrus/Cromha-Expansion-plugin#103]
**Describe the bug**
<Describe with the most words possible the bug that occurred.>The `Empire Quantum Metal` says it gives 25,000 credits on landing, even though it only has an `income` value of 15,000.

**To Reproduce**
<Write the steps to reproduce the behavior. You can add or delete existing steps.>
1. Go to a save that has this or the (plugin editor)[https://github.com/quyykk/plugin-editor]
2. Scroll down to find the outfit
3. See error

**Expected behavior**
That the data and text would be in agreement.

**Screenshots**

<img width="300" alt="Screen Shot 2023-07-15 at 6 49 42 AM" src="https://github.com/OcelotWalrus/Cromha-Expansion-plugin/assets/125756761/a80f08ad-8de2-4821-bb30-58b02dd82566">

**Game Logs**
N/A, different sort of bug.

**Additional context**
Cool plugin!

**Comment by lumbar527** [comment]
Oh, and another instance: in the Empire Start, the banker tells you that you have an interest rate of 0.8% or something, which is much higher than it actually is.

**Comment by OcelotWalrus** [comment]
First, thanks for reporting the bug, since I recently buffed and did other kind of slight modifications, it didn't updated/verified the descriptions. It fixed it with commit [`9b19fa1`](https://github.com/OcelotWalrus/Cromha-Expansion-plugin/commit/9b19fa1110f1e13414f80399fbc815c20f1693c7).

**Comment by OcelotWalrus** [comment]
Also thank you for saying it's a cool plugin :)
