### ISSUE TITLE
FEATURE: Descriptions Revamp

### ISSUE THREAD

**Issue by OcelotWalrus** [OcelotWalrus/Cromha-Expansion-plugin#104]
**Describe the solution you'd like**

Most planet/spaceport/item/ships descriptions are not finished, deprecated and more... Update all the descriptions!

**Comment by lumbar527** [comment]
Screenshots and notes of descriptions (Just noting now, will make some suggestions soon):
<img width="1680" alt="Screen Shot 2023-07-14 at 2 28 02 PM" src="https://github.com/OcelotWalrus/Cromha-Expansion-plugin/assets/125756761/f6e79093-0017-47a2-ac60-0de5fce6f7c9">
Not Korath remix
<img width="1680" alt="Screen Shot 2023-07-14 at 2 21 37 PM" src="https://github.com/OcelotWalrus/Cromha-Expansion-plugin/assets/125756761/79ea3914-433d-46ac-8344-078d16110ab4">
1) Not Wardragon, 2) Wardragon is misspelled.
<img width="597" alt="Screen Shot 2023-07-14 at 9 14 27 AM" src="https://github.com/OcelotWalrus/Cromha-Expansion-plugin/assets/125756761/d3137cf4-4062-470c-b8bd-db8b02d12bf0">
Same description
<img width="1680" alt="Screen Shot 2023-07-14 at 9 13 53 AM" src="https://github.com/OcelotWalrus/Cromha-Expansion-plugin/assets/125756761/f61fc876-d2cf-4ab2-acb6-db857dc825f5">
Same as Wasp
<img width="1680" alt="Screen Shot 2023-07-14 at 9 13 36 AM" src="https://github.com/OcelotWalrus/Cromha-Expansion-plugin/assets/125756761/0b85a5d2-bbcd-458e-950b-06133787b6b7">
Not Behemoth
<img width="1680" alt="Screen Shot 2023-07-14 at 9 13 33 AM" src="https://github.com/OcelotWalrus/Cromha-Expansion-plugin/assets/125756761/a791adaa-914a-4933-88d9-59bce4f38b52">
Not Bulk Freighter

**Comment by lumbar527** [comment]
Here's another one:
<img width="1680" alt="Screen Shot 2023-07-15 at 12 48 33 PM" src="https://github.com/OcelotWalrus/Cromha-Expansion-plugin/assets/125756761/53a0c851-ceb0-40ba-9d28-279e6b6002e9">
Same as Flivver

**Comment by OcelotWalrus** [comment]
Thank you for helping me. I think what I'll do tomorrow is just going through all descriptions to revamp them entirely. Same for outfits.

**Comment by OcelotWalrus** [comment]
Only the vanilla ships variants are left.

**Comment by OcelotWalrus** [comment]
I finished everything.

**Comment by OcelotWalrus** [comment]
But you can still suggest your idea if you'd like to.

**Comment by lumbar527** [comment]
I'm not good at writing descriptions, especially for other people's ships, because I don't know what the ships are supposed to be.
