### ISSUE TITLE
BUG: Mission won't trigger

### ISSUE THREAD

**Issue by lumbar527** [OcelotWalrus/Cromha-Expansion-plugin#114]
**Describe the bug**
Mission, Empire: Escort Convit won't offer.<Describe with the most words possible the bug that occurred.>

**To Reproduce**
<Write the steps to reproduce the behavior. You can add or delete existing steps.>
1. Do the Empire storyline until the Defense Solifar mission
2. Do the Defense Solifar mission
3. See error

**Expected behavior**
I expected the mission to offer.

**Game Logs**
[Uploading errors.txt…]()

**Additional context**
I already looked in `errors.txt` and found this:
```
Warning: Skipping unrecognized NPC completion condition "escort":
file "/Users/tabris/repos/roger/Cromha-Expansion-plugin/data/Empire/empire storyline 1.txt"
L362:   mission "Empire: Escort Convoit"
L385:     npc save escort

Warning: Skipping unrecognized personality "save":
file "/Users/tabris/repos/roger/Cromha-Expansion-plugin/data/Empire/empire storyline 1.txt"
L362:   mission "Empire: Escort Convoit"
L385:     npc save escort
L387:       personality save escort timid
```
Sorry, forgot about this for some time. I'll try fixing the errors in a bit.

**Comment by OcelotWalrus** [comment]
Fixing that right now.

**Comment by OcelotWalrus** [comment]
By the way you didn't waited long enough for the `errors.txt` files upload.
