### ISSUE TITLE
FEATURE: Cheat Plugin Support

### ISSUE THREAD

**Issue by lumbar527** [OcelotWalrus/Cromha-Expansion-plugin#120]
**Is your feature request related to a problem? Please describe.**
Yes, I want to use something to help outfit new ships but the editor does weird things.

**Describe the solution you'd like**
There should be everything shipyards/outfitters to be used in cheat plugins. (Like Omnis, World Forge)

**Describe alternatives you've considered**
- Use the plugin editor: No, that does weird things.
- Use the ship viewer: Doesn't support macs.

**Additional context**
**I'm already working on this:**
- [x] Empire Ships
- [x] Empire Outfits
- [x] Far Remnant Ships
- [x] Far Remnant Outfits?
- [x] Empire Rebel Ships
- [x] Empire Rebel Outifts
- [x] Lumbarian Empire Ships
- [x] Lumbarian Empire Outfits
- [x] Sentar (Quarg/Sheragi) Stuff Ships
- [x] Sentar Stuff Outfits

**Comment by OcelotWalrus** [comment]
Sure I'll work on it. Everything that is marked done is what I'm doing.

> Use the ship viewer: Doesn't support macs.

If you're searching for an alternative, check my website:
https://ocelotwalrus.github.io/endless-sky-ship-builder2.0/

**Comment by lumbar527** [comment]
Sorry, not that ship builder but the one where you can see variants and outfit loadouts of different ships.

**Comment by OcelotWalrus** [comment]
Actually could you let me take care of all the cheat stuff?

**Comment by lumbar527** [comment]
Sure, most of what I was thinking of doing was adding everything shipyard/outfitters. Here's what I've got so far: [world forge.txt](https://github.com/OcelotWalrus/Cromha-Expansion-plugin/files/12164243/world.forge.txt)

**Comment by OcelotWalrus** [comment]
Don't worry I'll take care of everything.

**Comment by lumbar527** [comment]
Thanks!

**Comment by OcelotWalrus** [comment]
[I've made this so far](https://github.com/OcelotWalrus/Cromha-Expansion-plugin/blob/main/data/devs-cheats.txt). The only that needs to be done is the outfitter & the shipyard definition.

**Comment by lumbar527** [comment]
> If you have any other attributes idea for the Cheater Core, tell me!

You forgot `"jump range" 7777777` What about it giving you hull/shields? Maybe make it a weapon?
For the description (Something like it):
`What a fascinating creation, the Cheater Core is. Made even more so by the fact that it does not exist. This think has everything you could want, along with some things you did not think to want.`
It should have the ability to pass through _all_ wormholes.
What about cloaking?
**What if the Cheater Core was everything?**

Can I work on an image? I have a great idea.

**Comment by OcelotWalrus** [comment]
Thanks for you help!

**Comment by lumbar527** [comment]
How about this for the Cheater Core (I could make it a little brighter if that would be good):
![cheater core](https://github.com/OcelotWalrus/Cromha-Expansion-plugin/assets/125756761/7daeda48-e023-47a3-ae05-5ddf8269028d)
P.S. It's the one ring.

**Comment by OcelotWalrus** [comment]
Sure.

> P.S. It's the one ring.

Yeah i figured it out fast. I see you really like the Lord Of The Ring/The Hobbit. Me too by the way.

**Comment by OcelotWalrus** [comment]
> You forgot "jump range" 7777777 What about it giving you hull/shields? Maybe make it a weapon?
For the description (Something like it):
What a fascinating creation, the Cheater Core is. Made even more so by the fact that it does not exist. This think has everything you could want, along with some things you did not think to want.
> It should have the ability to pass through all wormholes.
> What about cloaking?
> What if the Cheater Core was everything?
> 
> Can I work on an image? I have a great idea.

Check b9d4539

**Comment by OcelotWalrus** [comment]
> How about this for the Cheater Core (I could make it a little brighter if that would be good):
![cheater core](https://github.com/OcelotWalrus/Cromha-Expansion-plugin/assets/125756761/7daeda48-e023-47a3-ae05-5ddf8269028d)
P.S. It's the one ring.

Send me the blender mod and the final sprite when it's done please

**Comment by lumbar527** [comment]
c10679531d9746071e4d400df85c2c065f1551ff

Not sure what else to add to it.

**Comment by OcelotWalrus** [comment]
That's good thanks.

**Comment by OcelotWalrus** [comment]
The Cromha Empire is so advanced:
```
# Empire
		# Engines
	`RC-001 Atomic Engines`
	`RC-140 Atomic Thruster`
	`RC-160 Atomic Thruster`
	`RC-180 Atomic Thruster`
	`RC-200 Atomic Thruster`
	`RC-220 Atomic Thruster`
	`RX-120 Reverse Thruster`
	`RX-180 Reverse Thruster`
	`RX-200 Reverse Thruster`
	`RC-145 Atomic Steering`
	`RC-165 Atomic Steering`
	`RC-185 Atomic Steering`
	`RC-205 Atomic Steering`
	`RC-225 Atomic Steering`
	"Disruption Afterburnner"
		
		# Power
	"Empire Hai Chasm Batteries"
	"Empire Hai Fissure Batteries"
	"Empire Hai Gorge Batteries"
	"Empire Hai Ravine Batteries"
	"Empire Hai Valley Batteries"
	"Multiphasic Capacitor"
	"Phasic Radiothermal"
	"Phasic Dwarf Core"
	"Phasic Fission Reactor"
	"Thermal Nucleavoltaic"
	"RC-X1 Multiphasic Reactor"
	"RC-X2 Multiphasic Reactor"
	"RC-X3 Multiphasic Reactor"
	"RC-X4 Multiphasic Reactor"
	"Quantum Generator"
	
		# Weapons
	"Empire Particle gun"
	"Twin Empire Particle"
	"Empire Particle Turret"
	"Empire Particle Turret (Augmented)"
	"Ion Proton Gun"
	"Ion Proton Turret"
	"Multiphasic Anti-Missile"
	"Antimatter Railgun"
	"Empire Torpedo Bank"
	"Empire Typhoon Bank"
	"Empire Nuke"
	"Grab-Strike Blaze"
	"Langrage Empire-Heaver"
	"Alldust Beam Canon"
	"Alldust Beam Turret"
	"Nuclavoltaic Repeater"
	"Nuclavoltaic Turret"
	"Phasic Mine Layer"
	"Wel'y Beam Canon"
	"Wel'y Beam Turret"
	"Dual Wel'y Beam Turret"
	"Scrambling Beam"
	
		# Ammunition Stuff
	"Multiphasic ammo"
	"Multiphasic Ammo Rack"
	"Empire Torpedo Rack"
	"Empire Torpedo Missile"
	"Phasic-Cluster Mine"
	"Phasic Mine Rack"
	
		# Systems
	"Mineria Key Stone"
	"Fuel Capacitor"
	"X-Skirmish Computer"
	"X-Battlezone Computer"
	"X-Warforge Computer"
	"X-Crusade Computer"
	"Nanobot Pod"
	"Cloaking Module"
	"Empire Navy Emitter"
	"Countermesure Module"
	"Countermesure Module Compact"
	"Fuel Cell"
	"Weapon Module"
	"Engine Module"
	"Hull Breaker"
	"T1 Phasic Amplifier"
	"T2 Phasic Amplifier"
	"T3 Phasic Amplifier"
	"Phasic Ramscoop"
	"Ameliorating Phasic-Cell"
	"Phasic Reasoning Node"
	"Antimatter Capacitor"
	"Antimatter Capacitor (Large)"
	"Quatalant Shield (Tiny)"
	"Quatalant Shield (Small)"
	"Quatalant Shield (Medium)"
	"Quatalant Shield (Big)"
	"Quatalant Shield (Huge)"
	"Shield Processor"
	"Shield Processor (Huge)"
	"Compact Plasma Drive"
	"Plasma Drive"
	"Multiphasic Cooler"
	"Tre-Phasic Cooler"
	"One-Phasic Cooler"
	"NGx3 Quatalant Cooler"
	"NGx9 Quatalant Cooler"
	"Antimatter Cooling Cell"
	"Multiphasic Scanner"
	"Plasma Fuel Pod"
	"Empire Mapper"
	
		# Hand to Hand
	"Teleportation Dock"
	"Phasic Rifle"
	"Tre-Phasic Rifle"
	"Phasic Grenades"
	"Empire Barricade"
	"Empire Defense Station"
	"Medical Station"
	
		# Prototypes
	"RV-120 Disruption Thruster"
	"RV-120 Disruption Steering"
	"RV-170 Disruption Thruster"
	"RV-170 Disruption Steering"
	"Tri-Phasic Hyperdrive"
	"Caltalytic Tear Secret"
	"Caltalytic Tear"
	"Anti-Missile Field Device"
	"Draining Field Device"
	"Prototype Fusion Cannon (Empire)"
	"Dragonflame Cannon (Empire)"
```

**Comment by lumbar527** [comment]
> That's good thanks.

You're welcome. Have you noticed I like Lord of the Rings?

**Comment by OcelotWalrus** [comment]
I finished the Empire cheater sales. I'm gonna test the cheater stuffs.

**Comment by OcelotWalrus** [comment]
It seems to work fine.

**Comment by OcelotWalrus** [comment]
> Sorry, not that ship builder but the one where you can see variants and outfit loadouts of >different ships.
>
>This one: https://github.com/robot-rover/endless-sky-viewer

Thank you for making me discovering this program. I'm now gonna use it. By the way, you said it wasn't for mac but it's just a Java Program, so you can build the software yourself and use it if you're knowing how to and if you have java installed.

**Comment by OcelotWalrus** [comment]
Well it don't seems to work very well for me. There is nothing showing up.
![image](https://github.com/OcelotWalrus/Cromha-Expansion-plugin/assets/87318892/10c6d951-6e37-4635-8116-23dff5406dec)

**Comment by OcelotWalrus** [comment]
Hey @lumbar527 . Actually, could you take care of the Lumbarian ships & outfits please?

It's [this file](https://github.com/OcelotWalrus/Cromha-Expansion-plugin/blob/main/data/devs-cheats.txt) that you'll need to modifiy.

**Comment by lumbar527** [comment]
Working on it, just need to manage to commit before you edit the file. (I know it's possible to resolve conflicts but I don't know a lot of GitHub stuff)

**Comment by OcelotWalrus** [comment]
thanks!

**Comment by lumbar527** [comment]
You're welcome, though most of it was copy-pasting from `lumbarian sales.txt`. I just labeled some of the outfits.

**Comment by OcelotWalrus** [comment]
Sure that's okay.

**Comment by OcelotWalrus** [comment]
I made the last commit https://github.com/OcelotWalrus/Cromha-Expansion-plugin/commit/1d9ce55ee34ea74e66632aec5ee625ceb968d2ec. I think the Cheater Core is finished: you have access to all ships & outfits, you also have jobs that are like the plugin "World Forge".

You should test it yourself.
