### ISSUE TITLE
MidnightPlugins

### ISSUE THREAD

**Issue by MidnightPlugins** [OcelotWalrus/Cromha-Expansion-plugin#127]
### Location

copyright

### Describe the issue

Hello OcelotWalrus. Please give attribution to "Michael Arsollon" instead of "MidnightPlugins" as specified in the copyright files for my plugins regarding any data or image assets that need to be attributed to me. Welcome to plugin creation and thank you for enjoying my plugins!

### Expected content

Attributions to "Michael Arsollon" for data or image assets originating from plugins created under the  <https://github.com/MidnightPlugins> account.

**Comment by lumbar527** [comment]
I'll fix that.

**Comment by lumbar527** [comment]
Is 65c98745f23ffec5b52e1b87721bd81ac5a55b68 what you want?

**Comment by MidnightPlugins** [comment]
> Is [65c9874](https://github.com/OcelotWalrus/Cromha-Expansion-plugin/commit/65c98745f23ffec5b52e1b87721bd81ac5a55b68) what you want?

While specific attributions would be ideal, this is an improvement over the original. Thank you for that.

**Comment by lumbar527** [comment]
I'll ask if @OcelotWalrus will add specific things, but I'll close this for now.
