### ISSUE TITLE
Specific Attribution

### ISSUE THREAD

**Issue by lumbar527** [OcelotWalrus/Cromha-Expansion-plugin#128]
### Location

Copyright

### Describe the issue

@OcelotWalrus, could you add specific attribution to the copyright file? By that I mean having a copyright entry for different images and state who you sourced it from. (Thanks to MidnightPlugins for reporting this in #127)

### Expected content

It is expected that you have copyright entries for different files.

<details><summary>Examples</summary>
<p>

```
Files:
 images/something
Copyright: name, either yours or who you sourced it from.
License: CC-BY-SA-4.0
Comment: (If you used your name) Derived from works of <person> (if true:) under the same license.
```

</p>
</details>

**Comment by OcelotWalrus** [comment]
Sure, I'll work on that as soon as I can.

**Comment by OcelotWalrus** [comment]
@MidnightPlugins and @lumbar527 . I've used too much resources from other content creators. What I'm gonna do is totally make the plugin again. What I mean by that, is rebalancing stuff, creating my own textures.

I already delete the Ka'het/ and the Sheragi/ folder, I will create my own code instead of copying others.

I'm sorry @MidnightPlugins for taking your textures...

**Comment by lumbar527** [comment]
It's fine to use other people's plugin things as long as they're under an open source license and you give credit. I guess it would be simpler, though, to remake things on your own so you don't have to note everything. (Quick note—if you make something with someone's blender files, then it's good to give them credit.

**Comment by OcelotWalrus** [comment]
Yes that what's I'm doing, I'm re-makeing all textures that I've taken from someone else and I try to do the model myself.

I also competely delete the Sheragi/ directory because it's literally a plugin I have copied. Instead of coping I still have the textures but I will code all ships myself.

**Comment by OcelotWalrus** [comment]
> (Quick note—if you make something with someone's blender files, then it's good to give them credit.

That's why there is the templates/ folder inside of every blender model I made.
