### ISSUE TITLE
FEATURE: New Galaxy Far Away (Sentar Galaxy)

### ISSUE THREAD

**Issue by OcelotWalrus** [OcelotWalrus/Cromha-Expansion-plugin#84]
**Describe the solution you'd like**
It could be cool if there was a new galaxy called "Sentar" that is very far from the Milky Way and which is governed by the Cromha Empire in part and a brand new species with interesting lore and outfits/ships. This is a very basic idea for now but it can be a good idea.

**Comment by OcelotWalrus** [comment]
I created a new branch called "sentar-galaxy". It's where all the work will be done. The "sentar-galaxy" branch will be merge with the "devs" branch every time there is an update.

If you're planning on contributing/helping with the Sentar galaxy, please make sure you're on the wright branch.

**Comment by lumbar527** [comment]
You don't have a `sentar-galaxy` branch, at least on GitHub.

**Comment by OcelotWalrus** [comment]
I know I removed it. It's now on the main branch. If you want to check out the galaxy, go here:
![image](https://github.com/OcelotWalrus/Cromha-Expansion-plugin/assets/87318892/ba22ddc7-7309-4e93-aeaf-257f5c319a15)
In the Helk'Alk system with a Mineria Key Stone.

**Comment by OcelotWalrus** [comment]
I'm closing this and creating a discussion: https://github.com/OcelotWalrus/Cromha-Expansion-plugin/discussions/112
